### ISSUE TITLE
Missing Commas in Code Frame & Clipboard Issue on Firefox

### ISSUE THREAD

**Issue by heytheretyo** [remotion-dev/spring-editor#7]
Hi, I've encountered a minimal problem regarding the code frame when generating a snippet. It seems like **the commas are missing** for some reason, maybe some problem in parsing with the package or some sort.

![image](https://github.com/remotion-dev/spring-editor/assets/142723158/745370d0-e106-4911-a62f-5efa30d44be8)

And also, there is a bit of a fault on the clipboard compatibility, maybe because I am using Firefox but just to shade the issue.

![image](https://github.com/remotion-dev/spring-editor/assets/142723158/8648d453-d946-4549-8c6c-b211d603165a)

Thank your for your attention.

**Comment by JonnyBurger** [comment]
I fixed the commas now!

The clipboard uses an API that Firefox will only support from tomorrow on, it looks like?
I hope this will fix itself when you get the browser update.

<img width="789" alt="image" src="https://github.com/remotion-dev/spring-editor/assets/1629785/b6d26efb-864a-4f89-a497-15fc1939106c">

**Comment by heytheretyo** [comment]
Thanks for the update!
